export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";

export const ORDER_SAVE_REQUEST = "ORDER_SAVE_REQUEST";
export const ORDER_SAVE_SUCCESS = "ORDER_SAVE_SUCCESS";
export const ORDER_SAVE_FAIL = "ORDER_SAVE_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";



