export const CATE_LIST_REQUEST = "CATE_LIST_REQUEST";
export const CATE_LIST_SUCCESS = "CATE_LIST_SUCCESS";
export const CATE_LIST_FAIL = "CATE_LIST_FAIL";

export const CATE_SAVE_REQUEST = "CATE_SAVE_REQUEST";
export const CATE_SAVE_SUCCESS = "CATE_SAVE_SUCCESS";
export const CATE_SAVE_FAIL = "CATE_SAVE_FAIL";

export const CATE_DEL_REQUEST = "CATE_DEL_REQUEST";
export const CATE_DEL_SUCCESS = "CATE_DEL_SUCCESS";
export const CATE_DEL_FAIL = "CATE_DEL_FAIL";