export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_ORDER_SUCCESS = "PRODUCT_ORDER_SUCCESS";
export const PRODUCT_FILTER_SUCCESS = "PRODUCT_FILTER_SUCCESS";

export const PRODUCT_CATE_REQUEST = "PRODUCT_CATE_REQUEST";
export const PRODUCT_CATE_SUCCESS = "PRODUCT_CATE_SUCCESS";
export const PRODUCT_CATE_FAIL = "PRODUCT_CATE_FAIL";
export const PRODUCT_CATE_FILTER = "PRODUCT_CATE_FILTER";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
export const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS";
export const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";

