export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const USER_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const USER_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const USER_CONTACT_REQUEST = "USER_CONTACT_REQUEST";
export const USER_CONTACT_SUCCESS = "USER_CONTACT_SUCCESS";
export const USER_CONTACT_FAIL = "USER_CONTACT_FAIL";

export const LIST_CONTACT_REQUEST = "LIST_CONTACT_REQUEST";
export const LIST_CONTACT_SUCCESS = "LIST_CONTACT_SUCCESS";
export const LIST_CONTACT_FAIL = "LIST_CONTACT_FAIL";

export const DELMUTIL_CONTACT_REQUEST = "DELMUTIL_CONTACT_REQUEST";
export const DELMUTIL_CONTACT_SUCCESS = "DELMUTIL_CONTACT_SUCCESS";
export const DELMUTIL_CONTACT_FAIL = "DELMUTIL_CONTACT_FAIL";